<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_article_detail' => 'Detall article',
    'underconstruction' => 'En construcció',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
  ),
);


/* Auto generated by Themes Administration on : 2014.03.27 00:39:24 */
