<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['protocol'] = "mail";
$config['mailpath'] = "/usr/sbin/sendmail";
$config['smtp_host'] = "";
$config['smtp_user'] = "";
$config['smtp_pass'] = "";
$config['smtp_port'] = "26";
$config['smtp_timeout'] = "30";
$config['mailtype'] = "html";
$config['charset'] = "utf-8";
$config['newline'] = "\r\n";


/* Auto generated by Settings Administration on : 2018.10.25 19:15:10 */
